# Generated by Django 5.0 on 2023-12-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='element',
            name='name',
        ),
        migrations.RemoveField(
            model_name='element',
            name='volume',
        ),
    ]
