# Generated by Django 5.0 on 2023-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_generator_remove_element_audio_remove_element_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generator',
        ),
        migrations.AddField(
            model_name='element',
            name='audio',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='volume',
            field=models.IntegerField(default=50),
        ),
    ]
