# Generated by Django 5.0 on 2023-12-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_generator_element_audio_element_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='audio',
            field=models.FileField(null=True, upload_to='Audios/', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='element',
            name='volume',
            field=models.IntegerField(default=50, help_text='Default volume is 50', verbose_name='Volume'),
        ),
    ]
