# Generated by Django 5.0 on 2023-12-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_element_audio_alter_element_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('elements', models.ManyToManyField(to='app1.element')),
            ],
        ),
    ]
