# Generated by Django 5.0 on 2023-12-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_soundscape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='volume',
        ),
    ]
