# Generated by Django 5.0 on 2024-01-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='history',
            name='soundscape',
        ),
        migrations.AddField(
            model_name='history',
            name='soundscape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.soundscape'),
        ),
    ]
