# Generated by Django 5.0 on 2024-01-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_history_datetime_remove_history_soundscape_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
